-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, SUM(PR.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT PR, OFFLINE_SALE OS
WHERE OS.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;
