-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM(SELECT T1.NAME, T1.DATETIME
  FROM ANIMAL_INS T1, ANIMAL_OUTS T2
 WHERE T1.ANIMAL_ID = T2.ANIMAL_ID(+)
   AND T2.DATETIME IS NULL
 ORDER BY T1.DATETIME)
 WHERE ROWNUM <= 3