-- 코드를 입력하세요
SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC, CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
WHERE 1=1
AND CRCC.CAR_ID = CRCRH.CAR_ID
AND CAR_TYPE = '세단'
AND TO_CHAR(START_DATE,'YYYYMM') = '202210'
ORDER BY CRCC.CAR_ID DESC;